name: Test trigger send

on:
  push:
    

jobs:
  trigger-build:
    runs-on: ubuntu-latest
    steps:
      - name: "repository dispatch"
        run: |
          curl -X POST https://api.github.com/repos/biskyt/test-action/dispatches \
          -H 'Accept: application/vnd.github.everest-preview+json' \
          -u ${{ secrets.TEST_PAT }} \
          --data '{"event_type": "ping", "client_payload": { "repository": "'"$GITHUB_REPOSITORY"'" }}'

      - name: workflow dispatch
        run: |
          curl \
            -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/biskyt/test-action/actions/workflows/test-1/dispatches \
            -d '{"ref":"ref"}'